jQuery(function ($) {
    var download_button = $('#configuration-download');

    // Create a blob object.
    var bb = new Blob(
        ["---\naudit:\n  exclude_vector_patterns: []\n  include_vector_patterns: []\n  link_templates: []\n  links: true\n  forms: true\n  cookies: true\nscope:\n  redundant_path_patterns: {}\n  dom_depth_limit: 10\n  exclude_path_patterns: []\n  exclude_content_patterns: []\n  include_path_patterns: []\n  restrict_paths: []\n  extend_paths: []\n  url_rewrites: {}\ninput:\n  values: {}\n  default_values:\n    \"(?i-mx:name)\": arachni_name\n    \"(?i-mx:user)\": arachni_user\n    \"(?i-mx:usr)\": arachni_user\n    \"(?i-mx:pass)\": 5543!%arachni_secret\n    \"(?i-mx:txt)\": arachni_text\n    \"(?i-mx:num)\": '132'\n    \"(?i-mx:amount)\": '100'\n    \"(?i-mx:mail)\": arachni@email.gr\n    \"(?i-mx:account)\": '12'\n    \"(?i-mx:id)\": '1'\n  without_defaults: false\n  force: false\nsession: {}\nbrowser_cluster:\n  pool_size: 6\n  job_timeout: 120\n  worker_time_to_live: 100\n  ignore_images: false\n  screen_width: 1600\n  screen_height: 1200\ndatastore:\n  report_path: \nhttp:\n  user_agent: Arachni/v1.0.6\n  request_timeout: 50000\n  request_redirect_limit: 5\n  request_concurrency: 20\n  request_queue_size: 500\n  request_headers: {}\n  cookies: {}\nchecks:\n- xss_dom_script_context\n- os_cmd_injection_timing\n- code_injection\n- xss\n- xss_dom\n- xss_dom_inputs\n- xss_path\n- response_splitting\n- sql_injection\n- ldap_injection\n- trainer\n- code_injection_timing\n- sql_injection_timing\n- file_inclusion\n- sql_injection_differential\n- rfi\n- source_code_disclosure\n- path_traversal\n- xss_tag\n- code_injection_php_input_wrapper\n- xpath_injection\n- csrf\n- xss_event\n- no_sql_injection_differential\n- unvalidated_redirect\n- session_fixation\n- no_sql_injection\n- xss_script_context\n- os_cmd_injection\n- common_files\n- backup_directories\n- backup_files\n- origin_spoof_access_restriction_bypass\n- interesting_responses\n- localstart_asp\n- webdav\n- captcha\n- unencrypted_password_forms\n- hsts\n- cookie_set_for_parent_domain\n- html_objects\n- insecure_cookies\n- emails\n- credit_card\n- password_autocomplete\n- form_upload\n- http_only_cookies\n- ssn\n- mixed_resource\n- private_ip\n- cvs_svn_users\n- common_directories\n- htaccess_limit\n- http_put\n- xst\n- allowed_methods\n- backdoors\n- directory_listing\nplatforms: []\nplugins: {}\nno_fingerprinting: false\nauthorized_by: \nurl: https://192.168.3.102/owncloud/\n"],
        { type : 'application/yaml' }
    );

    download_button.attr( 'href', window.URL.createObjectURL( bb ) );
    download_button.attr( 'download', '192.168.3.102-profile.afp' );
});
